### ISSUE TITLE
app-email-address-input

### ISSUE THREAD

**Issue by dannynader** [MainaWycliffe/angular-building-custom-form-control-demo#1]
app-email-address-input it is not turning red when it is invalid

**Comment by mainawycliffe** [comment]
You mean on individual fields of the email (username and email provider)

**Comment by dannynader** [comment]
as you see the last field turns red when it is invalid  but the field above it does not change to red when it is invalid please please advise

![untitled](https://user-images.githubusercontent.com/17280329/46738278-771fa480-cca6-11e8-87c0-0f3fa8d6c720.png)

**Comment by mainawycliffe** [comment]
For that, I believe the best way is implement a validation on the individual controls, where you can use patterns to check for errors in the username part and domain part, then highlight where the error is instead of highlighting both fields when the error is probably on a single field. This gives you a much better UX. That can only be accomplished inside the component wrapping around both.
